services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - ./jellyfin:/config
      - ${MEDIA_FOLDER}/movies:/media/movies
      - ${MEDIA_FOLDER}/tv:/media/tv
    ports:
      - "8096:8096"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8888
    env_file:
      - .env
    volumes:
      - ./qbittorrent:/config
      - ${MEDIA_FOLDER}/downloads:/downloads
    ports:
      - "8888:8888"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    env_file:
      - .env
    volumes:
      - ./sonarr:/config
      - ${MEDIA_FOLDER}/tv:/tv
      - ${MEDIA_FOLDER}/downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    env_file:
      - .env
    volumes:
      - ./lidarr:/config
      - ${MEDIA_FOLDER}/music:/music
      - ${MEDIA_FOLDER}/downloads:/downloads
    ports:
      - "8686:8686"
    restart: unless-stopped

  whisparr:
    image: hotio/whisparr:v3
    container_name: whisparr
    env_file:
      - .env
    volumes:
      - ./whisparr:/config
      - ${MEDIA_FOLDER}/paff:/paff
      - ${MEDIA_FOLDER}/downloads:/downloads
    ports:
      - "6969:6969"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    env_file:
      - .env
    volumes:
      - ./radarr:/config
      - ${MEDIA_FOLDER}/movies:/movies
      - ${MEDIA_FOLDER}/downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    env_file:
      - .env
    volumes:
      - ./prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    env_file:
      - .env
    volumes:
      - ./bazarr:/config
      - ${MEDIA_FOLDER}/movies:/movies
      - ${MEDIA_FOLDER}/tv:/tv
    ports:
      - "6767:6767"
    restart: unless-stopped

  i2pd:
    image: purplei2p/i2pd
    container_name: i2pd
    volumes:
      - ./i2pd:/var/lib/i2pd
      - ./i2pd/i2pd.conf:/etc/i2pd/i2pd.conf:ro
    ports:
      - "7656:7656"
    restart: unless-stopped
